language: java

jobs:
  include:
    - stage: "Tests"
      name: "Unit & Integration"
      script: "./gradlew :envoy-control-tests:cleanTest :envoy-control-tests:test --tests pl.allegro.tech.servicemesh.envoycontrol.HttpIdleTimeoutTest"
