admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 10000 }
dynamic_resources:
  lds_config: {ads: {}}
  cds_config: {ads: {}}
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: envoy-control-xds
node:
  cluster: test-cluster
  id: test-id
  metadata:
    ads: true
    proxy_settings:
      outgoing:
        dependencies:
          - service: "echo"

static_resources:
  clusters:
  - connect_timeout: 1s
    hosts:
    - socket_address:
        address: HOST_IP
        port_value: HOST_PORT
    - socket_address:
        address: HOST_IP
        port_value: HOST2_PORT
    http2_protocol_options: {}
    name: envoy-control-xds
  - name: local_service
    type: STATIC
    hosts:
      - socket_address:
          address: LOCAL_SERVICE_IP
          port_value: 5678
    connect_timeout: 1s
  - name: this_admin
    type: STATIC
    hosts:
      - socket_address:
          address: 127.0.0.1
          port_value: 10000
    connect_timeout:
      seconds: 1

  listeners:
  - name: default_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5000
    filter_chains:
      filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: egress_http
          rds:
            route_config_name: default_routes
            config_source:
              ads: {}
          http_filters:
          - name: envoy.router
  - name: ingress_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5001
    filter_chains:
      - filters:
          - name: envoy.http_connection_manager
            config:
              stat_prefix: ingress_http
              rds:
                route_config_name: ingress_secured_routes
                config_source:
                  ads: {}
              http_filters:
                - name: envoy.router