admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 10000 }
dynamic_resources:
  lds_config: {ads: {}}
  cds_config: {ads: {}}
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: envoy-control-xds
node:
  cluster: test-cluster
  id: test-id
  metadata:
    service_name: "SERVICE_NAME"
    ads: true
    ingress_host: "0.0.0.0"
    ingress_port: 5001
    egress_host: "0.0.0.0"
    egress_port: 5000
    use_remote_address: true
    access_log_enabled: false
    add_upstream_external_address_header: true
    has_static_secrets_defined: true
    resources_dir: "/etc/envoy/extra"
    proxy_settings:
      outgoing:
        dependencies:
          - service: "*"

static_resources:
  secrets:
    - name: server_cert
      tls_certificate:
        certificate_chain:
          filename: CERTIFICATE_CHAIN
        private_key:
          filename: PRIVATE_KEY
    - name: validation_context
      validation_context:
        trusted_ca:
          filename: TRUSTED_CA
  clusters:
  - connect_timeout: 1s
    hosts:
    - socket_address:
        address: HOST_IP
        port_value: HOST_PORT
    - socket_address:
        address: HOST_IP
        port_value: HOST2_PORT
    http2_protocol_options: {}
    name: envoy-control-xds
  - name: envoy-original-destination
    type: ORIGINAL_DST
    lb_policy: ORIGINAL_DST_LB
    original_dst_lb_config:
      use_http_header: true
    connect_timeout:
      seconds: 1
    http_protocol_options:
      allow_absolute_url: true
  - name: local_service
    type: STATIC
    hosts:
      - socket_address:
          address: LOCAL_SERVICE_IP
          port_value: 5678
    connect_timeout: 1s
  - name: this_admin
    type: STATIC
    hosts:
      - socket_address:
          address: 127.0.0.1
          port_value: 10000
    connect_timeout:
      seconds: 1
